# The name of this app. Must be unique within a project.
name: formacion-spring

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Java documentation
# (https://docs.platform.sh/languages/java.html#supported-versions)
# to find the supported versions for the 'java' type.
type: 'java:17'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: mvnw clean package

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: java -jar $JAVA_OPTS target/formacion.jar --server.port=8080